AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31 

Resources:
  PetBasicInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      MemorySize: 512
      CodeUri: functions/PetBasicInfo/
      Handler: index.handler
      Runtime: nodejs22.x
      Events:
        ApiBase:
          Type: Api
          Properties:
            Path: /pet/{petID}
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /pet/{petID}/{proxy+}
            Method: ANY
      Environment:
        Variables:
          JWT_SECRET: "" 
          JWT_BYPASS: ""
          MONGODB_URI: ""
          ALLOWED_ORIGINS: ""
          NODE_ENV: "development"

  UserRoutesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      MemorySize: 512
      CodeUri: functions/UserRoutes/
      Handler: index.handler
      Runtime: nodejs22.x
      Events:
        AccountRootOptions:
          Type: Api
          Properties:
            Path: /account
            Method: OPTIONS
        AccountRootPut:
          Type: Api
          Properties:
            Path: /account
            Method: PUT

        AccountUserIdDelete:
          Type: Api
          Properties:
            Path: /account/{userId}
            Method: DELETE
        AccountUserIdGet:
          Type: Api
          Properties:
            Path: /account/{userId}
            Method: GET
        AccountUserIdOptions:
          Type: Api
          Properties:
            Path: /account/{userId}
            Method: OPTIONS

        DeleteUserWithEmail:
          Type: Api
          Properties:
            Path: /account/delete-user-with-email
            Method: ANY

        GenerateEmailCode:
          Type: Api
          Properties:
            Path: /account/generate-email-code
            Method: ANY

        GenerateEmailCode2:
          Type: Api
          Properties:
            Path: /account/generate-email-code-2
            Method: ANY

        GenerateSmsCode:
          Type: Api
          Properties:
            Path: /account/generate-sms-code
            Method: ANY

        Login:
          Type: Api
          Properties:
            Path: /account/login
            Method: ANY

        Login2:
          Type: Api
          Properties:
            Path: /account/login-2
            Method: ANY

        Register:
          Type: Api
          Properties:
            Path: /account/register
            Method: ANY

        RegisterByEmail:
          Type: Api
          Properties:
            Path: /account/register-by-email
            Method: ANY

        RegisterByPhoneNumber:
          Type: Api
          Properties:
            Path: /account/register-by-phoneNumber
            Method: ANY

        RegisterEmail2:
          Type: Api
          Properties:
            Path: /account/register-email-2
            Method: ANY

        UpdateImage:
          Type: Api
          Properties:
            Path: /account/update-image
            Method: ANY

        UpdatePassword:
          Type: Api
          Properties:
            Path: /account/update-password
            Method: ANY

        VerifyEmailCode:
          Type: Api
          Properties:
            Path: /account/verify-email-code
            Method: ANY

        VerifySmsCode:
          Type: Api
          Properties:
            Path: /account/verify-sms-code
            Method: ANY

      Environment:
        Variables:
          TWILIO_ACCOUNT_SID: ""
          TWILIO_AUTH_TOKEN: ""
          TWILIO_VERIFY_SERVICE_SID: ""
          JWT_SECRET: ""
          JWT_BYPASS: ""
          MONGODB_URI: ""
          ALLOWED_ORIGINS: ""
          NODE_ENV: "development"
            